project:
  type: website
  output-dir: docs
  resources:
  - .nojekyll
  - CNAME

lang: "tr"

website:
  title: "Eda İklim"
  navbar:
    logo:
      alt: "Eda İklim Logosu"
      path: resimler/logo.png
    left:
      - href: index.qmd
        text: "Anasayfa"
      - about.qmd

format:
  html:
    theme:
      - litera
    css: styles.css
    toc: true



